  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata: 
    name: "jenkins"
    labels: 
      name: "jenkins"
  spec: 
    replicas: 1
    template: 
      metadata: 
        name: "jenkins"
        labels: 
          name: "jenkins"
      spec: 
        containers: 
          - name: "jenkins"
            image: "tjkemper/jenkins:0.4"
            ports: 
              - containerPort: 8080
              - containerPort: 50000
            volumeMounts: 
              - name: "jenkins-data"
                mountPath: "/var/jenkins_home"
              - name: "docker-socket"
                mountPath: "/var/run/docker.sock"
            #livenessProbe:
            #  httpGet:
            #    path: /
            #    port: 8080
            #  initialDelaySeconds: 60
            #  timeoutSeconds: 5
        volumes: 
          - name: "jenkins-data"
            awsElasticBlockStore:
              volumeID: vol-955b1940
              fsType: ext4
          - name: "docker-socket"
            hostPath:
              path: "/var/run/docker.sock"
