apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 8080
    - name: "slave"
      port: 50000
      targetPort: 50000
  selector:
    app: jenkins

