apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "jenkins"
  namespace: "operations"
  annotations:
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - jenkins.revatureops.com
    secretName: jenkins-tls
  rules:
  - host: jenkins.revatureops.com
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: 80
